### ISSUE TITLE
hallow-cli ssh and ssh-add should default to username@hostname for the key comment

### ISSUE THREAD

**Issue by alex** [hallowauth/hallow#31]

**Comment by paultag** [comment]
Yeah absolutely. I am debating putting `hallow` in there somewhere too, since it may be good to make the cert immediately identifiable. It would also let us handle key refresh a bit easier, since we can check the expiry of the named key cert (some of this will make more sense when I have the agent PR up). 

Thoughts?

**Comment by paultag** [comment]
Alternatively, we could use extensions to set the endpoint and do it that way, and leave the key Id as you described.

**Comment by alex** [comment]
Hmmm, I don't have a strong opinion on that. Using extensions to have the endpoint seems potentially quite handy though.

**Comment by paultag** [comment]
Yeah I think I prefer that as well. I'll keep that in mind in the upcoming changesets
