### ISSUE TITLE
SSH certs supported by gpg-agent?

### ISSUE THREAD

**Issue by tomberek** [hallowauth/hallow#40]
Using GPG's agent (using that to manage Yubikey), i attempted to sign an RSA key, which failed. That just needs to be enabled as a supported key type.

Next I attempted to obtain a key via `hallow-cli ssh-add`. I obtained a public key, but the cert was not added. Unsure if gpg-agent supports it, or if there is some API difference or what.

Testing with `eval $(ssh-agent)` worked fine.

**Comment by alex** [comment]
Do you want to file a second bug to enable RSA keys by default?

**Comment by tomberek** [comment]
I'm hesitant to enable by default, but perhaps as an option.

**Comment by alex** [comment]
It looks like as of 2016 at least, it did not support certificates: https://lists.gnupg.org/pipermail/gnupg-devel/2016-August/031427.html

**Comment by tomberek** [comment]
We found that. Not sure if it was ever resolved. @paultag ?

**Comment by paultag** [comment]
My understanding based on debugging ssh-agent vs gpg-agent is that the gpg agent, as it was deployed on Tom's computer, is not taking Certificates.

When we ran ssh-agent in the same terminal-session, with the same binary, `ssh-add` worked as expected. I was going to dig into this to see if that patch set send to the ML was ever landed (and it's a config flag or something), but it may be worth adding a check to see if we're talking to gpg-agent somehow and output a warning.

The behavior is confusing because it successfully inserts the related private key, just not the Certificate (which makes sense when you think about how agent talks over the line), which means users who are deeply technical with ssh but not certificates wind up seeing a new `ecdsa` key in their keyring, think everything's working, and then seeing it fail to connect (because it's not a Certificate).

Alternatively, after the insert, I could enumerate the keys, and check to see that the Certificate was actually written, and if not, output a warning and some next steps to debug.

Thoughts @tomberek and @alex ?

**Comment by alex** [comment]
I think I'd prefer checking based on "is this gpg-agent" if there's a way to do that. But I don't feel strongly.

**Comment by alex** [comment]
10 seconds reading the SSH agent RFC suggests there's no "get server name/version" API, so I guess we want to "verify that the cert was really added" 🤷‍♂

**Comment by paultag** [comment]
It does have a fairly unique socket name. But yeah I think checking writes is sensible. Will send a MR!

**Comment by alex** [comment]
@paultag I think we can close this at this point?

**Comment by paultag** [comment]
Yeah. I think after #51 will trigger with enough information for users to make an educated guess.

@tomberek re-open if you think it's worth doing more on this for now - I think the big next step here is to figure out what's up with gpg-agent and certs
